name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: devops-sqli-projet
  REGION: europe-west1
  REPOSITORY: westfield-frontend
  SERVICE: demo-cloudrun

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v3
        with:
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.SERVICE_ACCOUNT }}

      - name: Setup Cloud SDK
        uses: google-github-actions/setup-gcloud@v3

      - name: Configure Docker
        run: |
          gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev --quiet

      - name: Build Docker image
        run: |
          docker build \
            -t ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.SERVICE }}:${{ github.sha }} .

      - name: Push Docker image
        run: |
          docker push \
            ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.SERVICE }}:${{ github.sha }}

      - name: Build Secret String
        id: secrets
        shell: bash
        run: |
          secrets_vars=$(paste -sd, .github/cloud-run/.demo.secrets.prod)
          echo "secrets_vars=$secrets_vars" >> "$GITHUB_OUTPUT"

      - name: Deploy to Cloud Run
        id: deploy
        uses: google-github-actions/deploy-cloudrun@v3
        with:
          project_id: ${{ env.PROJECT_ID }}
          service: ${{ env.SERVICE }}
          region: ${{ env.REGION }}
          image: ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.SERVICE }}:${{ github.sha }}

          secrets: ${{ steps.secrets.outputs.secrets_vars }}

          flags: >-
            --service-account=next-runtime@devops-sqli-projet.iam.gserviceaccount.com
            --env-vars-file=.github/cloud-run/.demo.env.prod
            --allow-unauthenticated

      - name: Show Cloud Run URL
        run: |
          echo "Application URL:"
          echo "${{ steps.deploy.outputs.url }}"